on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
      - run: bun i
      - run: bun semantic-release
        env:
          # - [npm \| Granular Access Token]( https://www.npmjs.com/settings/snomiao/tokens/granular-access-tokens/new )
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  
          # WITH https://github.com/snomiao/snobuild/settings/actions Read and write permission
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
